language: csharp
sudo: required

install:
  - sudo apt-get update && sudo apt-get install npm && sudo apt-get install nodejs
  - sudo ln -s /usr/bin/nodejs /usr/bin/node

services:
  - docker

before_script:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"

script: 
  - cd ./SmarterBalanced.SampleItems/src/SmarterBalanced.SampleItems.Web
  - dotnet restore ../
  - dotnet build 
  - npm install 
  - grunt all
  - cd /home/travis/build/osu-cass/SampleItemsWebsite/
  - dotnet test ./SmarterBalanced.SampleItems/src/SmarterBalanced.SampleItems.Test/project.json
  # TODO: Run typescript tests

matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
    dotnet: 1.0.0-preview2-1-003177
    mono: none

#Docker section
after_success:
  - docker --version
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - eval $(aws ecr get-login --region us-west-2)
  - dotnet publish /home/travis/build/osu-cass/SampleItemsWebsite/SmarterBalanced.SampleItems/src/SmarterBalanced.SampleItems.Web -o /home/travis/build/osu-cass/SampleItemsWebsite/publish/
  - cd /home/travis/build/osu-cass/SampleItemsWebsite/publish/
  - docker build -t sampleitemscode .
  - docker tag sampleitemscode:latest 047189625337.dkr.ecr.us-west-2.amazonaws.com/sampleitemscode:$BRANCH
  - docker push 047189625337.dkr.ecr.us-west-2.amazonaws.com/sampleitemscode:$BRANCH
  - cd /home/travis/build/osu-cass/SampleItemsWebsite
  - chmod ugo+x DeployScripts/runEcsBuild.sh
  - ./DeployScripts/runEcsBuild.sh
